### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cfarthing03** [MaterialFoundry/MaterialDeck#121]
- OS: Windows
 - Browser: Foundry App, OperaGX
 - Module version: 1.7.2
 - Foundry version: 11.315
 - Gaming system & version: dnd5e 
 - Any other modules enabled: yes

When using FXmaster the color option doesn't seem to affect the weather controls, though it still works with the color filter

Whenever I activate the effect the console log gets spammed with 2681 errors. Most of them look to be the same thing just repeated. I've sent 3 of them below.

commons.js:2070 Error: You are accessing the DrawingDocument#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:2059:19)
    at DrawingDocument._logV10CompatibilityWarning (commons.js:8544:14)
    at get data [as data] (commons.js:8432:24)
    at Vehicles._refreshVehicleMap (vehicles.js:331:58)
    at Vehicles._refreshState (vehicles.js:309:10)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13738:13)
    at foundry.js:13711:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry.js:13711:33)
l

commons.js:2070 Error: You are accessing the Scene#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:2059:19)
    at Scene._logV10CompatibilityWarning (commons.js:8544:14)
    at get data [as data] (commons.js:8432:24)
    at Vehicles._refreshVehicleMap (vehicles.js:330:35)
    at Vehicles._refreshState (vehicles.js:309:10)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13738:13)
    at foundry.js:13711:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry.js:13711:33)
l

commons.js:2070 Error: You are accessing the DrawingDocument#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:2059:19)
    at DrawingDocument._logV10CompatibilityWarning (commons.js:8544:14)
    at get data [as data] (commons.js:8432:24)
    at Vehicles._refreshVehicleMap (vehicles.js:331:58)
    at Vehicles._refreshState (vehicles.js:309:10)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13738:13)
    at foundry.js:13711:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry.js:13711:33)
l

**Comment by farling42** [comment]
Just as a note, OperaGX isn't a supported browser because of the limitations it places on the canvas.

**Comment by MaterialFoundry** [comment]
With the release of MD v2 I assume this issue is fixed (assuming FXMaster is also updated to the latest version and a supported browser is used).
If it isn't, feel free to reopen this issue.
